# Generated by Django 3.1.1 on 2020-12-12 02:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alu', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_alu', models.CharField(help_text='5 caracteres - Ej. AL000', max_length=10, verbose_name='Codigo')),
                ('ape_alu', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nom_alu', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('dni_alu', models.CharField(help_text='8 digitos', max_length=8, verbose_name='D.N.I.')),
                ('dire_alu', models.CharField(max_length=250, verbose_name='Direccion de domicilio')),
                ('barra_alu', models.DecimalField(decimal_places=0, help_text='12 digitos', max_digits=13, verbose_name='Codigo de barras')),
                ('email_alu', models.CharField(max_length=50, verbose_name='Email personal')),
                ('celular_alu', models.IntegerField(help_text='9 digitos', verbose_name='Celular')),
                ('papa_alu', models.CharField(max_length=250, verbose_name='Apellidos y nombres del padre')),
                ('mama_alu', models.CharField(max_length=250, verbose_name='Apellidos y nombres de la madre')),
                ('imagen_alu', models.CharField(max_length=350, verbose_name='Fotografia')),
                ('pass_alu', models.CharField(max_length=120, verbose_name='Password')),
                ('tiposesion', models.CharField(default='ALUMNO', max_length=12, verbose_name='Tipo de sesion')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'alumnos',
                'db_table': 'alumnos',
                'ordering': ['ape_alu'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosAsistencia',
            fields=[
                ('id_asis', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asis', models.DateField(verbose_name='Fecha que asistio')),
            ],
            options={
                'verbose_name': 'Alumno - asistencia',
                'verbose_name_plural': 'alumnos - asistencias',
                'db_table': 'alumnos_asistencia',
                'ordering': ['alumnos_id_alu'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnosNotas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota1_nota', models.DecimalField(decimal_places=2, default=0, help_text='Ej. 10.30 -- ( 0 a 20)', max_digits=4, verbose_name='Nota 1')),
                ('nota2_nota', models.DecimalField(decimal_places=2, default=0, help_text='Ej. 10.30 -- ( 0 a 20)', max_digits=4, verbose_name='Nota 2')),
                ('promedio_nota', models.DecimalField(decimal_places=2, help_text='(Nota 1 + Nota 2)/2', max_digits=4, verbose_name='Promedio')),
            ],
            options={
                'verbose_name': 'Alumno - nota',
                'verbose_name_plural': 'alumnos - notas',
                'db_table': 'alumnos_notas',
                'ordering': ['alumnos_id_alu'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_bibli', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_bibli', models.CharField(max_length=6)),
                ('titulo_bibli', models.CharField(max_length=100)),
                ('autor_bibli', models.CharField(max_length=100)),
                ('editorial_bibli', models.CharField(max_length=100)),
                ('edicion_bibli', models.DecimalField(decimal_places=0, max_digits=4)),
                ('isbn_bibli', models.CharField(max_length=12)),
                ('stock_bibli', models.DecimalField(decimal_places=0, max_digits=3)),
                ('barra_bibli', models.DecimalField(decimal_places=0, help_text='12 digitos', max_digits=13, verbose_name='Codigo de barras')),
                ('disponible_bibli', models.BooleanField(default=True)),
                ('imagen_bibli', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'biblioteca',
                'db_table': 'biblioteca',
                'ordering': ['titulo_bibli'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BibliotecaPrestamo',
            fields=[
                ('id_bipre', models.AutoField(primary_key=True, serialize=False)),
                ('fechapres_bipre', models.DateField()),
                ('fechadevo_bipre', models.DateField()),
            ],
            options={
                'verbose_name': 'biblioteca - prestamo',
                'verbose_name_plural': 'biblioteca - prestamos',
                'db_table': 'biblioteca_prestamo',
                'ordering': ['fechapres_bipre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BibliotecaPrestamoDetalle',
            fields=[
                ('id_bpd', models.AutoField(primary_key=True, serialize=False)),
                ('entrego_bpd', models.IntegerField()),
            ],
            options={
                'verbose_name': 'biblioteca - prestamo detalle',
                'verbose_name_plural': 'biblioteca - prestamos detalles',
                'db_table': 'biblioteca_prestamo_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.IntegerField(help_text='Llega del FrontEnd', primary_key=True, serialize=False)),
                ('fecha_check', models.DateField(verbose_name='Fecha de ID Stripe')),
            ],
            options={
                'verbose_name_plural': 'checkouts',
                'db_table': 'checkout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nom_curso', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'cursos',
                'ordering': ['nom_curso'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursosComple',
            fields=[
                ('id_cuco', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad_cuco', models.IntegerField()),
                ('tipo_cuco', models.CharField(max_length=50)),
                ('nom_cuco', models.TextField()),
                ('fechaini_cuco', models.DateField()),
                ('fechafin_cuco', models.DateField()),
                ('precio_cuco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('detalle_cuco', models.TextField()),
                ('imagen_cuco', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'Curso complementario',
                'verbose_name_plural': 'cursos complementarios',
                'db_table': 'cursos_comple',
                'ordering': ['fechaini_cuco'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_doce', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_doce', models.CharField(max_length=10, verbose_name='Codigo:')),
                ('ape_doce', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nom_doce', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('dni_doce', models.CharField(help_text='8 digitos', max_length=8, verbose_name='D.N.I')),
                ('email_doce', models.CharField(max_length=50, verbose_name='Email')),
                ('celular_doce', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Celular')),
                ('barra_doce', models.DecimalField(decimal_places=0, help_text='12 digitos', max_digits=13, verbose_name='Codigo de barras')),
                ('cv_doce', models.TextField(verbose_name='Curriculum')),
                ('imagen_doce', models.CharField(max_length=350)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.SlugField(help_text='Campo creado para el apellido', unique=True, verbose_name='Slug del Apellido')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'docentes',
                'db_table': 'docentes',
                'ordering': ['ape_doce'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factu', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal_factu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igv_factu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_factu', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'facturacion',
                'db_table': 'facturacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('turno_hora', models.CharField(max_length=10)),
                ('anio_hora', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dia_hora', models.CharField(max_length=9)),
                ('hoini_hora', models.TimeField()),
                ('hofin_hora', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'horario',
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id_libre', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_libre', models.CharField(max_length=6, verbose_name='Codigo')),
                ('titulo_libre', models.CharField(max_length=100, verbose_name='Titulo')),
                ('autor_libre', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial_libre', models.CharField(max_length=100, verbose_name='Editorial')),
                ('edicion_libre', models.DecimalField(decimal_places=0, help_text='Ej.: 2010', max_digits=4, verbose_name='Edicion')),
                ('isbn_libre', models.CharField(help_text='12 Digitos', max_length=12, verbose_name='ISBN')),
                ('stock_libre', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Stock')),
                ('precio_libre', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('barra_libre', models.DecimalField(decimal_places=0, help_text='13 digitos', max_digits=13, verbose_name='Codigo de barras')),
                ('disponible_libre', models.BooleanField(default=True, verbose_name='Disponible?')),
                ('imagen_libre', models.CharField(max_length=350, verbose_name='Foto')),
                ('detalle_libre', models.TextField(verbose_name='Detalle del Libro')),
                ('recomendado_libre', models.BooleanField(default=True, verbose_name='Recomendado?')),
            ],
            options={
                'verbose_name': 'libreria',
                'verbose_name_plural': 'libreria',
                'db_table': 'libreria',
                'ordering': ['titulo_libre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibreriaPedido',
            fields=[
                ('codigo_lipe', models.IntegerField(help_text='5 caracteres - Ej. 10000', primary_key=True, serialize=False, verbose_name='Codigo del Pedido')),
                ('fecha_lipe', models.DateField(verbose_name='Fecha de Pedido')),
                ('entrego_lpd', models.BooleanField(verbose_name='¿Entregado?')),
            ],
            options={
                'verbose_name': 'Libreria - pedido',
                'verbose_name_plural': 'libreria - pedidos',
                'db_table': 'libreria_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibreriaPedidoDetalle',
            fields=[
                ('id_lpd', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_lpd', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('descuento_lpd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Libreria - pedido detalle',
                'verbose_name_plural': 'libreria - pedidos detalles',
                'db_table': 'libreria_pedido_detalle',
                'ordering': ['libreria_pedido_codigo_lipe'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_mate', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mate', models.CharField(help_text='Nombre de la materia', max_length=50, verbose_name='Nombre de la Materia')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materia',
                'db_table': 'materia',
                'ordering': ['nom_mate'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_mat', models.CharField(max_length=5, verbose_name='Codigo de Matricula')),
                ('anio_mat', models.IntegerField(default='2020', help_text='Ej. 2020', verbose_name='Año')),
                ('detalle_mat', models.TextField(verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'matriculas',
                'db_table': 'matricula',
                'ordering': ['codigo_mat'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id_sec', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sec', models.CharField(max_length=5)),
                ('aula_sec', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'secciones',
                'db_table': 'secciones',
                'ordering': ['nom_sec'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('dni_usu', models.CharField(help_text='8 digitos', max_length=8, verbose_name='D.N.I.')),
                ('ape_usu', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nom_usu', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('dire_usu', models.CharField(max_length=250, verbose_name='Dirección')),
                ('email_usu', models.CharField(max_length=50, verbose_name='Email')),
                ('celular_usu', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Celular')),
                ('fecha_usu', models.DateField(auto_now=True, help_text='AAAA-MM-DD', verbose_name='Fecha de inscripción')),
                ('imagen_usu', models.CharField(max_length=350)),
                ('activo', models.BooleanField(default=True, help_text='Activo: 1 - Inactivo: 0', verbose_name='Activo')),
                ('slug', models.SlugField(help_text='Slug del APELLIDO', max_length=150)),
                ('pass_usu', models.CharField(max_length=120, verbose_name='Password')),
                ('tiposesion', models.CharField(default='USUARIO', max_length=12, verbose_name='Tipo de sesion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'ordering': ['ape_usu'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='E-Mail')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Esta activo?')),
                ('is_staff', models.BooleanField(blank=True, default=True, verbose_name='Es del Equipo?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/imagen')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona Contraseña',
                'verbose_name_plural': 'Personas Contraseñas',
                'ordering': ['date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona Detalles',
                'verbose_name_plural': 'Personas Detalles',
            },
        ),
    ]
